app_name = "HelloWorld"

[head]
javascript_includes = [
  "/js/index.js",
]
css_includes = [
  "/css/index.css",
  "https://fonts.googleapis.com/css?family=Robot"
]
raw_tags = [
]

[body]
app_id = "js-sample-app"
nodes = [
  "<div>Footer</div>"
]
